module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:jsx-a11y/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
    'plugin:sonarjs/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: [
    'react',
    '@typescript-eslint',
    'jsx-a11y',
    'import',
    'sonarjs',
  ],
  rules: {
    'react/react-in-jsx-scope': 'off',
    'react/prop-types': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': ['warn'],
    'sonarjs/cognitive-complexity': ['error', 15],
    'sonarjs/no-duplicate-string': ['error', 5],
    'jsx-a11y/alt-text': ['error'],
    'jsx-a11y/anchor-has-content': ['error'],
    'jsx-a11y/anchor-is-valid': ['error'],
    'jsx-a11y/aria-props': ['error'],
    'jsx-a11y/aria-role': ['error'],
    'jsx-a11y/aria-unsupported-elements': ['error'],
    'jsx-a11y/click-events-have-key-events': ['warn'],
    'jsx-a11y/heading-has-content': ['error'],
    'jsx-a11y/html-has-lang': ['error'],
    'jsx-a11y/img-redundant-alt': ['error'],
    'jsx-a11y/interactive-supports-focus': ['warn'],
    'jsx-a11y/label-has-associated-control': ['error'],
    'jsx-a11y/media-has-caption': ['warn'],
    'jsx-a11y/mouse-events-have-key-events': ['warn'],
    'jsx-a11y/no-access-key': ['error'],
    'jsx-a11y/no-autofocus': ['warn'],
    'jsx-a11y/no-distracting-elements': ['error'],
    'jsx-a11y/no-interactive-element-to-noninteractive-role': ['error'],
    'jsx-a11y/no-noninteractive-element-interactions': ['warn'],
    'jsx-a11y/no-noninteractive-element-to-interactive-role': ['error'],
    'jsx-a11y/no-redundant-roles': ['error'],
    'jsx-a11y/role-has-required-aria-props': ['error'],
    'jsx-a11y/role-supports-aria-props': ['error'],
    'jsx-a11y/scope': ['error'],
    'jsx-a11y/tabindex-no-positive': ['warn'],
  },
  settings: {
    react: {
      version: 'detect',
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
      typescript: {},
    },
  },
};
