[build]
  command = "npm run build"
  publish = ".next"
  environment = { GO_VERSION = "1.19", NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GO_VERSION = "1.19"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "next"
  targetPort = 3000
