[build]
  command = "npm install && npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-cache"
