[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Production context
[context.production]
  command = "npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"
