[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "10.8.2"
  NEXT_PUBLIC_SITE_URL = "https://toolsfree.online"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
